#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Oct  8 11:48:08 2019

@author: rudi
coba membuat bilangan random
mencari siapa yang akan menjadi parent

"""
import random
nilai_random=[0]*10
for i in range(10):
    nilai_random[i] = random.random()
    
def parentCrossover(nilai_random, crossoverRatio):
    find_pair = []
    pair=[]
    for i in range(len(nilai_random)):
        if nilai_random[i] < crossoverRatio:
            find_pair.append(i)
            if len(find_pair) == 2:
                pair.append(find_pair)
                find_pair =[]
#    if len(find_pair) == 1:
#        temp = int(random.random()*len(nilai_random))
#        while temp==find_pair[0]:
#            temp = int(random.random()*len(nilai_random))
#        find_pair.append(temp)
#        pair.append(find_pair)
    return pair
print(nilai_random)
print(parentCrossover(nilai_random, 0.5))